---
title: "Analysis"
author: "Annmarie Thomson, Arya Sardesai, Christina Zhang"
date: "2025-1-3"
output: html_document
---

```{r}
set.seed(2024)
library(vroom)
library(tidyverse)
library(tidymodels)
library(ggplot2)
library(ucimlrepo)
```

## Markdown:

```{r read and clean data}
bike <- fetch_ucirepo(id = 275)
bike_data <- bike$data$original
bike_data <- bike_data %>%
  select(-instant, -dteday)
write_csv(bike_data, "../data/bike_data.csv")

```

```{r}
ggplot(bike_data, (aes(x = cnt))) +
   geom_histogram(bins = 30) +
  labs(title = "Distribution of Bike Usage", y = "Count", x = "Amount of Rides")

bike_split = initial_split(bike_data, prop = 0.8, strata = cnt)
bike_train = training(bike_split)
bike_test = testing(bike_split)

bike_train_summary <- bike_train %>%
  summarize(median_use = median(cnt),
            mean_use = mean(cnt),
            standard_deviation_use = sd(cnt))

bike_test_summary <- bike_test %>%
  summarize(median_use = median(cnt),
            mean_use = mean(cnt),
            standard_deviation_use = sd(cnt))

bike_total_summary <- bind_rows(bike_train_summary, bike_test_summary) %>%
  mutate(partition = c("Train", "Test"),
         fraction = c(0.8, 0.2)) %>%
  relocate(partition, fraction)

```
