name: r_env
channels:
  - conda-forge
dependencies:
  - r-base=4.2.2  
  - r-cowplot=1.1.3
  - r-devtools=2.4.3
  - r-kknn=1.3.1
  - r-scales=1.1.1
  - r-testthat=3.1.2
  - r-tidymodels=1.2.0
  - r-tidyverse=2.0.0
  - r-tinytex=0.37
  - r-usethis=2.1.5
  - r-vroom=1.5.7
  - unixodbc=2.3.9
  - r-renv  
  - r-rmarkdown  

